GET http://localhost:3001/api/expenses/2023-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiaWQiOiI2NGM1YTJmMTNhYjMxMGZhNjVkZmNjZTkiLCJpYXQiOjE2OTA3MzczMDUsImV4cCI6MTY5MTM0MjEwNX0.1-TMw7gCjfSj_1Dm7KnmHqHtVfxuiMkm25FiKdWIJFA

###
GET https://expense-tracker-123213.fly.dev/api/expenses/2023-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiaWQiOiI2NGM1YTJmMTNhYjMxMGZhNjVkZmNjZTkiLCJpYXQiOjE2OTA3MjQ0MjB9.XHPUxxA5vN22m1dQeJrYfj_l0_6X1iAMGJJsSsUJcqs